#!/bin/sh

echoerr() { echo "$@" 1>&2; }
fail() { echoerr $1; exit 1; }
ERR_WORDPRESS="Error configuring wordpress"
ERR_EXEC="Error executing wordpress"

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi

# Copy wordpress installation to PATH_HTML if it does not exist
[ -e "$FILE_WP_CONF" ] || cp -RT "$PATH_WP_INSTALL" "$PATH_HTML"                          || fail "$ERR_WORDPRESS"
# Generate WP_SALTS
WP_SALTS=${WP_SALTS:-$(wget -q -O - https://api.wordpress.org/secret-key/1.1/salt/)}        || fail "$ERR_WORDPRESS"
# Envsubst config params to FILE_WP_CONFIG
envsubst "$VARIABLES_WP_CONF" < "$SRC_WP_CONF" > "$FILE_WP_CONF"                            || fail "$ERR_WORDPRESS"
# Configure sendmail_path in php.ini to allow wordpress sending emails
# Configure max_execution_time in php.ini to allow installation of heavier plugins
TEMP_PHP_INI="/tmp/php.ini"
cat "$FILE_PHP_INI" | \
    sed "s|;sendmail_path.*|sendmail_path = $BIN_SENDMAIL|g" | \
    sed "s|max_execution_time.*|max_execution_time = $PHP_MAX_EXECUTION_TIME|g" | \
    sed "s|upload_max_filesize.*|upload_max_filesize = $PHP_UPLOAD_MAX_FILESIZE|g" \
    > "$TEMP_PHP_INI"                                                                       || fail "$ERR_WORDPRESS"
cat "$TEMP_PHP_INI" > "$FILE_PHP_INI"                                                       || fail "$ERR_WORDPRESS"


# Start the app
$EXEC_APACHE_VARNISH $@                                                                     || fail "$ERR_EXEC"
